public struct QueryCodeGenerator {
    public static func generate(from file: ParsedQueryFile, structName: String) -> String {
        var lines: [String] = []
        lines.append("// Generated by PostgresModels — do not edit")
        lines.append("#if canImport(FoundationEssentials)")
        lines.append("import FoundationEssentials")
        lines.append("#else")
        lines.append("import Foundation")
        lines.append("#endif")
        lines.append("import Logging")
        lines.append("import PostgresNIO")
        lines.append("")
        lines.append("struct \(structName) {")
        for (i, query) in file.queries.enumerated() {
            if i > 0 { lines.append("") }
            lines.append(contentsOf: generateQuery(query))
        }
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Per-query generation

    private static func generateQuery(_ query: ParsedQuery) -> [String] {
        var lines: [String] = []
        let funcName = IdentifierSanitizer.functionName(from: query.name)
        let sql = normalizedSQL(query.sql, params: query.params)

        // Build parameter list lines
        var paramLines: [String] = ["        _ db: some PostgresQueryRunner,"]
        for p in query.params {
            paramLines.append("        \(IdentifierSanitizer.columnName(from: p.name)): \(p.type),")
        }
        paramLines.append("        logger: Logger")

        let returnClause: String
        switch query.kind {
        case .one:   returnClause = " -> \(oneTupleType(query.returns))?"
        case .many:  returnClause = " -> [\(oneTupleType(query.returns))]"
        case .exec:  returnClause = ""
        }

        lines.append("    static func \(funcName)(")
        lines.append(contentsOf: paramLines)
        lines.append("    ) async throws\(returnClause) {")
        lines.append(contentsOf: generateBody(query, sql: sql))
        lines.append("    }")
        return lines
    }

    private static func generateBody(_ query: ParsedQuery, sql: String) -> [String] {
        switch query.kind {
        case .one:
            return generateOneBody(query, sql: sql)
        case .many:
            return generateManyBody(query, sql: sql)
        case .exec:
            return [
                "        try await db.query(",
                "            \"\(sql)\",",
                "            logger: logger",
                "        )",
            ]
        }
    }

    private static func generateOneBody(_ query: ParsedQuery, sql: String) -> [String] {
        let decodeType = decodeTypeExpr(query.returns)
        let destructure = destructureExpr(query.returns)
        let construct = constructExpr(query.returns)
        var lines = [
            "        let rows = try await db.query(",
            "            \"\(sql)\",",
            "            logger: logger",
            "        )",
            "        for try await \(destructure) in rows.decode(\(decodeType).self) {",
        ]
        lines.append(contentsOf: conversionLines(query.returns, indent: "            "))
        lines.append("            return \(construct)")
        lines.append("        }")
        lines.append("        return nil")
        return lines
    }

    private static func generateManyBody(_ query: ParsedQuery, sql: String) -> [String] {
        let tupleType = oneTupleType(query.returns)
        let decodeType = decodeTypeExpr(query.returns)
        let destructure = destructureExpr(query.returns)
        let construct = constructExpr(query.returns)
        var lines = [
            "        var results: [\(tupleType)] = []",
            "        for try await \(destructure) in try await db.query(",
            "            \"\(sql)\",",
            "            logger: logger",
            "        ).decode(\(decodeType).self) {",
        ]
        lines.append(contentsOf: conversionLines(query.returns, indent: "            "))
        lines.append("            results.append(\(construct))")
        lines.append("        }")
        lines.append("        return results")
        return lines
    }

    // MARK: - Type expression helpers

    /// Return type for :one — `(id: UUID, name: String)` or bare type for single column.
    /// Custom types are exposed as their RawRepresentable type (e.g. `EventVisibility`).
    private static func oneTupleType(_ returns: [ParsedReturn]) -> String {
        if returns.count == 1 { return returns[0].type }
        let inner = returns.map { "\(IdentifierSanitizer.columnName(from: $0.name)): \($0.type)" }.joined(separator: ", ")
        return "(\(inner))"
    }

    /// Element type to decode for one return: its built-in type, or the raw
    /// backing type (`String`/`Int`/…) for a custom RawRepresentable type.
    private static func decodeElement(_ r: ParsedReturn) -> String {
        guard r.isCustom else { return r.type }
        let base = r.backing ?? "String"
        return r.type.hasSuffix("?") ? "\(base)?" : base
    }

    /// Decode type passed to `.decode(_:)` — `(String, String)` or `UUID` for single.
    private static func decodeTypeExpr(_ returns: [ParsedReturn]) -> String {
        if returns.count == 1 { return decodeElement(returns[0]) }
        let inner = returns.map(decodeElement).joined(separator: ", ")
        return "(\(inner))"
    }

    /// Name bound in the `for try await` pattern. Custom columns bind the raw
    /// value under a `…Raw` name, which the conversion lines then convert.
    private static func boundName(_ r: ParsedReturn) -> String {
        let n = IdentifierSanitizer.columnName(from: r.name)
        return r.isCustom ? "\(n)Raw" : n
    }

    /// Destructuring pattern — `(idRaw, name)` or `id` for single
    private static func destructureExpr(_ returns: [ParsedReturn]) -> String {
        if returns.count == 1 { return boundName(returns[0]) }
        let names = returns.map(boundName).joined(separator: ", ")
        return "(\(names))"
    }

    /// Lines converting raw values of custom columns into their
    /// RawRepresentable types. A non-optional invalid value throws; an
    /// optional one becomes `nil`.
    private static func conversionLines(_ returns: [ParsedReturn], indent: String) -> [String] {
        var lines: [String] = []
        for r in returns where r.isCustom {
            let final = IdentifierSanitizer.columnName(from: r.name)
            let raw = "\(final)Raw"
            let base = r.type.hasSuffix("?") ? String(r.type.dropLast()) : r.type
            if r.type.hasSuffix("?") {
                lines.append("\(indent)let \(final) = \(raw).flatMap { \(base)(rawValue: $0) }")
            } else {
                lines.append("\(indent)guard let \(final) = \(base)(rawValue: \(raw)) else {")
                lines.append("\(indent)    throw PostgresModelsError.invalidRawValue(column: \"\(r.name)\", rawValue: \"\\(\(raw))\")")
                lines.append("\(indent)}")
            }
        }
        return lines
    }

    /// Labeled tuple construction — `(id: id, name: name)` or bare identifier for single column
    private static func constructExpr(_ returns: [ParsedReturn]) -> String {
        if returns.count == 1 { return IdentifierSanitizer.columnName(from: returns[0].name) }
        let parts = returns.map { r -> String in
            let n = IdentifierSanitizer.columnName(from: r.name)
            return "\(n): \(n)"
        }
        return "(\(parts.joined(separator: ", ")))"
    }

    // MARK: - SQL normalization

    /// Collapses multi-line SQL to one line, strips trailing semicolon,
    /// replaces $1/$2/… with \(paramName) for postgres-nio interpolation.
    private static func normalizedSQL(_ sql: String, params: [ParsedParam]) -> String {
        var result = sql
            .components(separatedBy: .newlines)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        if result.hasSuffix(";") { result = String(result.dropLast()) }
        // Escape characters unsafe in a Swift string literal
        result = result.replacingOccurrences(of: "\\", with: "\\\\")
        result = result.replacingOccurrences(of: "\"", with: "\\\"")
        for (i, param) in params.enumerated().reversed() {
            let swiftName = IdentifierSanitizer.columnName(from: param.name)
            let binding: String
            if param.isCustom {
                // Bind the enum's raw value. Optionals propagate via `?.rawValue`.
                binding = param.type.hasSuffix("?") ? "\(swiftName)?.rawValue" : "\(swiftName).rawValue"
            } else {
                binding = swiftName
            }
            result = result.replacingOccurrences(of: "$\(i + 1)", with: "\\(\(binding))")
        }
        return result
    }
}
