public struct QueryCodeGenerator {
    public static func generate(from file: ParsedQueryFile, structName: String) -> String {
        var lines: [String] = []
        lines.append("// Generated by PostgresModels — do not edit")
        lines.append("#if canImport(FoundationEssentials)")
        lines.append("import FoundationEssentials")
        lines.append("#else")
        lines.append("import Foundation")
        lines.append("#endif")
        lines.append("import Logging")
        lines.append("import PostgresNIO")
        lines.append("")
        lines.append("struct \(structName) {")
        for (i, query) in file.queries.enumerated() {
            if i > 0 { lines.append("") }
            lines.append(contentsOf: generateQuery(query))
        }
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Per-query generation

    private static func generateQuery(_ query: ParsedQuery) -> [String] {
        var lines: [String] = []
        let funcName = IdentifierSanitizer.functionName(from: query.name)
        let sql = normalizedSQL(query.sql, params: query.params)

        // Build parameter list lines
        var paramLines: [String] = ["        _ db: some PostgresQueryRunner,"]
        for p in query.params {
            paramLines.append("        \(IdentifierSanitizer.columnName(from: p.name)): \(p.type),")
        }
        paramLines.append("        logger: Logger")

        let returnClause: String
        switch query.kind {
        case .one:   returnClause = " -> \(oneTupleType(query.returns))?"
        case .many:  returnClause = " -> [\(oneTupleType(query.returns))]"
        case .exec:  returnClause = ""
        }

        lines.append("    static func \(funcName)(")
        lines.append(contentsOf: paramLines)
        lines.append("    ) async throws\(returnClause) {")
        lines.append(contentsOf: generateBody(query, sql: sql))
        lines.append("    }")
        return lines
    }

    private static func generateBody(_ query: ParsedQuery, sql: String) -> [String] {
        switch query.kind {
        case .one:
            return generateOneBody(query, sql: sql)
        case .many:
            return generateManyBody(query, sql: sql)
        case .exec:
            return [
                "        try await db.query(",
                "            \"\(sql)\",",
                "            logger: logger",
                "        )",
            ]
        }
    }

    private static func generateOneBody(_ query: ParsedQuery, sql: String) -> [String] {
        let decodeType = decodeTypeExpr(query.returns)
        let destructure = destructureExpr(query.returns)
        let construct = constructExpr(query.returns)
        return [
            "        let rows = try await db.query(",
            "            \"\(sql)\",",
            "            logger: logger",
            "        )",
            "        for try await \(destructure) in rows.decode(\(decodeType).self) {",
            "            return \(construct)",
            "        }",
            "        return nil",
        ]
    }

    private static func generateManyBody(_ query: ParsedQuery, sql: String) -> [String] {
        let tupleType = oneTupleType(query.returns)
        let decodeType = decodeTypeExpr(query.returns)
        let destructure = destructureExpr(query.returns)
        let construct = constructExpr(query.returns)
        return [
            "        var results: [\(tupleType)] = []",
            "        for try await \(destructure) in try await db.query(",
            "            \"\(sql)\",",
            "            logger: logger",
            "        ).decode(\(decodeType).self) {",
            "            results.append(\(construct))",
            "        }",
            "        return results",
        ]
    }

    // MARK: - Type expression helpers

    /// Return type for :one — `(id: UUID, name: String)` or bare type for single column
    private static func oneTupleType(_ returns: [ParsedReturn]) -> String {
        if returns.count == 1 { return returns[0].type }
        let inner = returns.map { "\(IdentifierSanitizer.columnName(from: $0.name)): \($0.type)" }.joined(separator: ", ")
        return "(\(inner))"
    }

    /// Decode type passed to `.decode(_:)` — `(UUID, String)` or `UUID` for single
    private static func decodeTypeExpr(_ returns: [ParsedReturn]) -> String {
        if returns.count == 1 { return returns[0].type }
        let inner = returns.map { $0.type }.joined(separator: ", ")
        return "(\(inner))"
    }

    /// Destructuring pattern — `(id, name)` or `id` for single
    private static func destructureExpr(_ returns: [ParsedReturn]) -> String {
        if returns.count == 1 { return IdentifierSanitizer.columnName(from: returns[0].name) }
        let names = returns.map { IdentifierSanitizer.columnName(from: $0.name) }.joined(separator: ", ")
        return "(\(names))"
    }

    /// Labeled tuple construction — `(id: id, name: name)` or bare identifier for single column
    private static func constructExpr(_ returns: [ParsedReturn]) -> String {
        if returns.count == 1 { return IdentifierSanitizer.columnName(from: returns[0].name) }
        let parts = returns.map { r -> String in
            let n = IdentifierSanitizer.columnName(from: r.name)
            return "\(n): \(n)"
        }
        return "(\(parts.joined(separator: ", ")))"
    }

    // MARK: - SQL normalization

    /// Collapses multi-line SQL to one line, strips trailing semicolon,
    /// replaces $1/$2/… with \(paramName) for postgres-nio interpolation.
    private static func normalizedSQL(_ sql: String, params: [ParsedParam]) -> String {
        var result = sql
            .components(separatedBy: .newlines)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        if result.hasSuffix(";") { result = String(result.dropLast()) }
        // Escape characters unsafe in a Swift string literal
        result = result.replacingOccurrences(of: "\\", with: "\\\\")
        result = result.replacingOccurrences(of: "\"", with: "\\\"")
        for (i, param) in params.enumerated().reversed() {
            let swiftName = IdentifierSanitizer.columnName(from: param.name)
            result = result.replacingOccurrences(of: "$\(i + 1)", with: "\\(\(swiftName))")
        }
        return result
    }
}
