public struct RuntimeCodeGenerator {
    /// Generates the shared `PostgresModelsRuntime.swift` file containing the
    /// `PostgresQueryRunner` abstraction. This lets generated query functions
    /// accept either a `PostgresClient` (one connection per call) or a
    /// `PostgresConnection` (e.g. inside `client.withTransaction { conn in … }`),
    /// so multiple generated calls can share a single transaction.
    public static func generate() -> String {
        let lines: [String] = [
            "// Generated by PostgresModels — do not edit",
            "import Logging",
            "import PostgresNIO",
            "",
            "/// Anything that can run a `PostgresQuery`. Both `PostgresClient` and",
            "/// `PostgresConnection` conform, so generated query functions can run",
            "/// against a pooled client or a single connection inside a transaction.",
            "protocol PostgresQueryRunner: Sendable {",
            "    @discardableResult",
            "    func query(_ query: PostgresQuery, logger: Logger, file: String, line: Int) async throws -> PostgresRowSequence",
            "}",
            "",
            "extension PostgresQueryRunner {",
            "    @discardableResult",
            "    func query(_ query: PostgresQuery, logger: Logger) async throws -> PostgresRowSequence {",
            "        try await self.query(query, logger: logger, file: #fileID, line: #line)",
            "    }",
            "}",
            "",
            "// `PostgresConnection.query(_:logger:file:line:)` already matches the",
            "// requirement (logger is non-optional), so an empty conformance suffices.",
            "extension PostgresConnection: PostgresQueryRunner {}",
            "",
            "// `PostgresClient.query` takes `logger: Logger?`, so it cannot witness the",
            "// requirement directly. This thin wrapper bridges the two. Promoting the",
            "// logger to `Logger?` before the inner call selects the original overload",
            "// and avoids recursing into this method.",
            "extension PostgresClient: PostgresQueryRunner {",
            "    func query(_ query: PostgresQuery, logger: Logger, file: String, line: Int) async throws -> PostgresRowSequence {",
            "        let optionalLogger: Logger? = logger",
            "        return try await self.query(query, logger: optionalLogger, file: file, line: line)",
            "    }",
            "}",
        ]
        return lines.joined(separator: "\n")
    }
}
